# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/lab7provided/mb_usb_hdmi_top.xdc

# Block Designs: bd/lab7_1_mb/lab7_1_mb.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab7_1_mb || ORIG_REF_NAME==lab7_1_mb} -quiet] -quiet

# IP: bd/lab7_1_mb/ip/lab7_1_mb_microblaze_0_0/lab7_1_mb_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab7_1_mb_microblaze_0_0 || ORIG_REF_NAME==lab7_1_mb_microblaze_0_0} -quiet] -quiet

# IP: bd/lab7_1_mb/ip/lab7_1_mb_dlmb_v10_0/lab7_1_mb_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab7_1_mb_dlmb_v10_0 || ORIG_REF_NAME==lab7_1_mb_dlmb_v10_0} -quiet] -quiet

# IP: bd/lab7_1_mb/ip/lab7_1_mb_ilmb_v10_0/lab7_1_mb_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab7_1_mb_ilmb_v10_0 || ORIG_REF_NAME==lab7_1_mb_ilmb_v10_0} -quiet] -quiet

# IP: bd/lab7_1_mb/ip/lab7_1_mb_dlmb_bram_if_cntlr_0/lab7_1_mb_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab7_1_mb_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==lab7_1_mb_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/lab7_1_mb/ip/lab7_1_mb_ilmb_bram_if_cntlr_0/lab7_1_mb_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab7_1_mb_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==lab7_1_mb_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/lab7_1_mb/ip/lab7_1_mb_lmb_bram_0/lab7_1_mb_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab7_1_mb_lmb_bram_0 || ORIG_REF_NAME==lab7_1_mb_lmb_bram_0} -quiet] -quiet

# IP: bd/lab7_1_mb/ip/lab7_1_mb_xbar_0/lab7_1_mb_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab7_1_mb_xbar_0 || ORIG_REF_NAME==lab7_1_mb_xbar_0} -quiet] -quiet

# IP: bd/lab7_1_mb/ip/lab7_1_mb_microblaze_0_axi_periph_0/lab7_1_mb_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab7_1_mb_microblaze_0_axi_periph_0 || ORIG_REF_NAME==lab7_1_mb_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/lab7_1_mb/ip/lab7_1_mb_microblaze_0_axi_intc_0/lab7_1_mb_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab7_1_mb_microblaze_0_axi_intc_0 || ORIG_REF_NAME==lab7_1_mb_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/lab7_1_mb/ip/lab7_1_mb_mdm_1_0/lab7_1_mb_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab7_1_mb_mdm_1_0 || ORIG_REF_NAME==lab7_1_mb_mdm_1_0} -quiet] -quiet

# IP: bd/lab7_1_mb/ip/lab7_1_mb_clk_wiz_1_0/lab7_1_mb_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab7_1_mb_clk_wiz_1_0 || ORIG_REF_NAME==lab7_1_mb_clk_wiz_1_0} -quiet] -quiet

# IP: bd/lab7_1_mb/ip/lab7_1_mb_rst_clk_wiz_1_100M_0/lab7_1_mb_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab7_1_mb_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==lab7_1_mb_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/lab7_1_mb/ip/lab7_1_mb_axi_uartlite_0_0/lab7_1_mb_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab7_1_mb_axi_uartlite_0_0 || ORIG_REF_NAME==lab7_1_mb_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/lab7_1_mb/ip/lab7_1_mb_hdmi_text_controller_0_3/lab7_1_mb_hdmi_text_controller_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab7_1_mb_hdmi_text_controller_0_3 || ORIG_REF_NAME==lab7_1_mb_hdmi_text_controller_0_3} -quiet] -quiet

# XDC: c:/Users/jacka/lab7_2try1/lab7_2try1.gen/sources_1/bd/lab7_1_mb/lab7_1_mb_ooc.xdc
