# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/jacka/finalproj_try1/finalproj_try1.srcs/sources_1/ip/titlescreen_320_240_rom_1/titlescreen_320_240_rom.xci
# IP: The module: 'titlescreen_320_240_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jacka/finalproj_try1/finalproj_try1.gen/sources_1/ip/titlescreen_320_240_rom_1/titlescreen_320_240_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'titlescreen_320_240_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/jacka/finalproj_try1/finalproj_try1.srcs/sources_1/ip/titlescreen_320_240_rom_1/titlescreen_320_240_rom.xci
# IP: The module: 'titlescreen_320_240_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jacka/finalproj_try1/finalproj_try1.gen/sources_1/ip/titlescreen_320_240_rom_1/titlescreen_320_240_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'titlescreen_320_240_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
