# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/erinm/Vivado_projects/ECE385-Work/final/proj_jack_4_23/finalproj_try1/finalproj_try1.srcs/sources_1/ip/ducks_rom/ducks_rom.xci
# IP: The module: 'ducks_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/erinm/Vivado_projects/ECE385-Work/final/proj_jack_4_23/finalproj_try1/finalproj_try1.gen/sources_1/ip/ducks_rom/ducks_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ducks_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/erinm/Vivado_projects/ECE385-Work/final/proj_jack_4_23/finalproj_try1/finalproj_try1.srcs/sources_1/ip/ducks_rom/ducks_rom.xci
# IP: The module: 'ducks_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/erinm/Vivado_projects/ECE385-Work/final/proj_jack_4_23/finalproj_try1/finalproj_try1.gen/sources_1/ip/ducks_rom/ducks_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ducks_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
