# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/jacka/lab7_justblock_diagram_nohdmi/lab7_justblock_diagram_nohdmi.srcs/sources_1/bd/lab7_1_mb/ip/lab7_1_mb_mdm_1_0/lab7_1_mb_mdm_1_0.xci
# IP: The module: 'lab7_1_mb_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jacka/lab7_justblock_diagram_nohdmi/lab7_justblock_diagram_nohdmi.gen/sources_1/bd/lab7_1_mb/ip/lab7_1_mb_mdm_1_0/lab7_1_mb_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab7_1_mb_mdm_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jacka/lab7_justblock_diagram_nohdmi/lab7_justblock_diagram_nohdmi.gen/sources_1/bd/lab7_1_mb/ip/lab7_1_mb_mdm_1_0/lab7_1_mb_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab7_1_mb_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/jacka/lab7_justblock_diagram_nohdmi/lab7_justblock_diagram_nohdmi.srcs/sources_1/bd/lab7_1_mb/ip/lab7_1_mb_mdm_1_0/lab7_1_mb_mdm_1_0.xci
# IP: The module: 'lab7_1_mb_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jacka/lab7_justblock_diagram_nohdmi/lab7_justblock_diagram_nohdmi.gen/sources_1/bd/lab7_1_mb/ip/lab7_1_mb_mdm_1_0/lab7_1_mb_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab7_1_mb_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jacka/lab7_justblock_diagram_nohdmi/lab7_justblock_diagram_nohdmi.gen/sources_1/bd/lab7_1_mb/ip/lab7_1_mb_mdm_1_0/lab7_1_mb_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab7_1_mb_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
