# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/jacka/lab7_justblock_diagram_nohdmi/lab7_justblock_diagram_nohdmi.srcs/sources_1/bd/lab7_1_mb/ip/lab7_1_mb_hdmi_text_controller_0_0/lab7_1_mb_hdmi_text_controller_0_0.xci
# IP: The module: 'lab7_1_mb_hdmi_text_controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/jacka/lab7_justblock_diagram_nohdmi/lab7_justblock_diagram_nohdmi.gen/sources_1/bd/lab7_1_mb/ip/lab7_1_mb_hdmi_text_controller_0_0/src/hdmi_tx_0/hdmi_tx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_0 || ORIG_REF_NAME==hdmi_tx_0} -quiet] -quiet

# IP: c:/Users/jacka/lab7_justblock_diagram_nohdmi/lab7_justblock_diagram_nohdmi.gen/sources_1/bd/lab7_1_mb/ip/lab7_1_mb_hdmi_text_controller_0_0/src/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: c:/Users/jacka/lab7_justblock_diagram_nohdmi/lab7_justblock_diagram_nohdmi.gen/sources_1/bd/lab7_1_mb/ip/lab7_1_mb_hdmi_text_controller_0_0/src/clk_wiz_0/clk_wiz_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/jacka/lab7_justblock_diagram_nohdmi/lab7_justblock_diagram_nohdmi.gen/sources_1/bd/lab7_1_mb/ip/lab7_1_mb_hdmi_text_controller_0_0/src/clk_wiz_0/clk_wiz_0_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/jacka/lab7_justblock_diagram_nohdmi/lab7_justblock_diagram_nohdmi.gen/sources_1/bd/lab7_1_mb/ip/lab7_1_mb_hdmi_text_controller_0_0/src/clk_wiz_0/clk_wiz_0_ooc.xdc

# IP: C:/Users/jacka/lab7_justblock_diagram_nohdmi/lab7_justblock_diagram_nohdmi.srcs/sources_1/bd/lab7_1_mb/ip/lab7_1_mb_hdmi_text_controller_0_0/lab7_1_mb_hdmi_text_controller_0_0.xci
# IP: The module: 'lab7_1_mb_hdmi_text_controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/jacka/lab7_justblock_diagram_nohdmi/lab7_justblock_diagram_nohdmi.gen/sources_1/bd/lab7_1_mb/ip/lab7_1_mb_hdmi_text_controller_0_0/src/hdmi_tx_0/hdmi_tx_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_0 || ORIG_REF_NAME==hdmi_tx_0} -quiet] -quiet

# IP: c:/Users/jacka/lab7_justblock_diagram_nohdmi/lab7_justblock_diagram_nohdmi.gen/sources_1/bd/lab7_1_mb/ip/lab7_1_mb_hdmi_text_controller_0_0/src/clk_wiz_0/clk_wiz_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: c:/Users/jacka/lab7_justblock_diagram_nohdmi/lab7_justblock_diagram_nohdmi.gen/sources_1/bd/lab7_1_mb/ip/lab7_1_mb_hdmi_text_controller_0_0/src/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/jacka/lab7_justblock_diagram_nohdmi/lab7_justblock_diagram_nohdmi.gen/sources_1/bd/lab7_1_mb/ip/lab7_1_mb_hdmi_text_controller_0_0/src/clk_wiz_0/clk_wiz_0_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/jacka/lab7_justblock_diagram_nohdmi/lab7_justblock_diagram_nohdmi.gen/sources_1/bd/lab7_1_mb/ip/lab7_1_mb_hdmi_text_controller_0_0/src/clk_wiz_0/clk_wiz_0_ooc.xdc
