# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/jacka/lab7wk1_try1/lab7wk1_try1.srcs/sources_1/bd/lab7_1_mb/ip/lab7_1_mb_xbar_0/lab7_1_mb_xbar_0.xci
# IP: The module: 'lab7_1_mb_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jacka/lab7wk1_try1/lab7wk1_try1.gen/sources_1/bd/lab7_1_mb/ip/lab7_1_mb_xbar_0/lab7_1_mb_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab7_1_mb_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/jacka/lab7wk1_try1/lab7wk1_try1.srcs/sources_1/bd/lab7_1_mb/ip/lab7_1_mb_xbar_0/lab7_1_mb_xbar_0.xci
# IP: The module: 'lab7_1_mb_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jacka/lab7wk1_try1/lab7wk1_try1.gen/sources_1/bd/lab7_1_mb/ip/lab7_1_mb_xbar_0/lab7_1_mb_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab7_1_mb_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
